Repository lev-Zero/lastpong, pull requests merged in 2022-12, with the labels that each got.

#19 Refactor: Header (zustand는 아직 미사용)
  frontend/src/components/Header.tsx
Labels: FE

#23 Style: LandingPage 버튼 포지셔닝 & xl Button 제작
  frontend/pages/index.tsx
  frontend/src/components/CustomButton.tsx
Labels: enhancement, FE

#25 Feature/game options
  frontend/pages/game/options.tsx
  frontend/pages/watch/index.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/MatchInfo.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/layouts/MainLayout.tsx
Labels: FE

#27 Feat/invitation modal
  frontend/pages/_app.tsx
  frontend/src/components/MainPage.tsx
  frontend/src/components/modal/Modal.tsx
  frontend/src/interfaces/UserProps.ts
Labels: FE

#28 feat: 게임 결과창 win | lose 모달로 표시기능 구현
  frontend/pages/game/index.tsx
Labels: FE

#37 feat: 채팅방 생성 모달 초안 구현
  frontend/pages/chat/index.tsx
Labels: FE

#46 feat:OTP 입력 실패시 오류표시후 입력칸 초기화
  frontend/src/components/OtpWindow.tsx
Labels: FE

#48 feat : 시작 페이지에서 버튼으로 페이크 유저 로그인 기능 구현
  frontend/pages/auth/basic/id.tsx
  frontend/pages/fakeLogin.tsx
  frontend/pages/index.tsx
Labels: FE

#49 feat:chat/:roomNo 뷰와 로직 일부 구현
  frontend/package.json
  frontend/pages/chat/[roomNo].tsx
Labels: FE

#65 feat:sidebar/userSearch 기능까지 구현 완
  frontend/pages/index.tsx
  frontend/src/components/Sidebar.tsx
Labels: FE

#67 Feat/addfriends
  frontend/pages/home.tsx
  frontend/pages/user/[username].tsx
  frontend/src/components/CustomButton.tsx
  frontend/src/stores/userStore.ts
Labels: FE

#76 BE game Invite event 추가
  backend/src/game/dto/game.dto.ts
  backend/src/game/game.gateway.ts
Labels: BE

#80 fix: 친구추가 창에서 본인이름 안뜨게 수정
  frontend/src/components/Sidebar.tsx
Labels: FE

#82 feat: AllUserStore만들고 이를 이용하여 친추추가 목록과 채팅방 대기인원 갱신
  frontend/pages/chat/index.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/stores/allUserStore.ts
Labels: FE
