Repository lev-Zero/lastpong, pull requests merged in 2023-01, with the labels that each got.

#106 feat: 비밀번호 넣는 모달과 입력까지 일 단 구현
  frontend/pages/chat/index.tsx
Labels: FE

#107 fix : private -> protected 안헷갈리게 + 자물쇠 하얗게
  frontend/pages/chat/[roomNo].tsx
  frontend/pages/chat/index.tsx
  frontend/public/lock-white.svg
  frontend/src/components/ChatRoomItem.tsx
  frontend/src/interfaces/ChatRoomItemProps.ts
  frontend/src/interfaces/ChatRoomProps.ts
  frontend/src/stores/chatStore.ts
Labels: FE

#111 feat: UserItem popover DM 초안
  frontend/src/components/UserItem.tsx
Labels: FE

#121 feat: chatRoom 에서 오른쪽 마우스 메뉴 초안 구현
  frontend/pages/chat/[roomNo].tsx
  frontend/public/green_crown.svg
  frontend/src/components/ChatUserItem.tsx
  frontend/src/components/OptionMenu.tsx
  frontend/src/interfaces/ChatUserItemProps.ts
Labels: FE, 진행상황 공유, 오류 질문

#126 fix: 비밀번호 맞았을때만 roomNo로 라우팅 기능 완성
  frontend/pages/chat/index.tsx
Labels: FE

#127 !FIX: Admin 주고 뺏기
  frontend/pages/chat/[roomNo].tsx
  frontend/pages/chat/index.tsx
  frontend/public/green_crown.svg
  frontend/src/components/ChatAdminOptionMenu.tsx
  frontend/src/components/ChatUserItem.tsx
  frontend/src/components/OptionMenu.tsx
  frontend/src/interfaces/ChatUserItemProps.ts
  frontend/src/stores/chatStore.ts
Labels: FE, 리팩토링

#145 feat : remove Friend 초안
  frontend/pages/chat/[roomNo].tsx
  frontend/src/components/ChatAdminOptionMenu.tsx
  frontend/src/stores/chatStore.ts
Labels: FE

#152 feat : dm 메세지 쌓이는 스택 구현
  frontend/src/components/UserItem.tsx
Labels: FE

#172 style: 한글 글씨체 추가
  frontend/styles/fonts/NanumSquareRoundEB.ttf
  frontend/styles/global.css
Labels: FE

#175 /watch, MatchInfo에 아바타 추가하였습니다.
  frontend/pages/game/options.tsx
  frontend/pages/watch/index.tsx
  frontend/src/components/MatchInfo.tsx
  frontend/src/interfaces/GamePlayerProps.ts
  frontend/src/interfaces/MatchInfoProps.ts
Labels: FE

#180 fix : 어드민 메뉴 뜨는 조건 수정
  frontend/src/components/ChatAdminOptionMenu.tsx
  frontend/src/components/ChatUserItem.tsx
Labels: FE

#192 feat: 게임끝나고 홈와도 메세지 스택 유지
  frontend/src/components/UserItem.tsx
  frontend/src/stores/chatStore.ts
Labels: FE

#194 !STYLE : game 오리지날 퐁처럼 예쁘게 만듦
  frontend/pages/game/[roomNo].tsx
  frontend/styles/fonts/Bungee-Regular.ttf
  frontend/styles/global.css
Labels: FE

#197 Fix/minor
  frontend/pages/user/[username].tsx
  frontend/src/components/CustomAlert.tsx
  frontend/src/components/UserItem.tsx
Labels: FE

#199 Cmoon/home/1.13
  frontend/package.json
  frontend/pages/auth/basic/id.tsx
  frontend/pages/chat/[roomNo].tsx
  frontend/pages/chat/index.tsx
  frontend/src/components/CustomAlert.tsx
  frontend/src/components/UserItem.tsx
  frontend/yarn.lock
Labels: FE

#208 feat: DM 전 상태확인 로직 추가
  frontend/src/components/CustomAlert.tsx
  frontend/src/components/UserItem.tsx
Labels: FE

#210 Cmoon/please/final
  frontend/pages/auth/basic/id.tsx
  frontend/pages/chat/[roomNo].tsx
  frontend/pages/chat/index.tsx
  frontend/public/nyan-cat-4k.gif
  frontend/src/components/ChatAdminOptionMenu.tsx
  frontend/src/components/UserItem.tsx
Labels: FE
